image: node:latest

variables:
  # workaround self-signed certificate 
  GIT_SSL_NO_VERIFY: "1"

before_script:
    - yarn install
    - yarn lint --fix

cache:
    paths:
        - node_modules/

test:node:latest:
    script:
        - yarn prepare
        - yarn test
        
test:lint:
    script:
        - yarn lint
        
#publish:
#    script:
#        - yarn prepare
#        - echo '//registry.npmjs.org/:_authToken=39f0b607-e179-4caf-bb63-9b63476e32b0'>.npmrc
#        - npm publish